export const actionsTypes = {
  SET_CART_OPEN: "SET_CART_OPEN",
  SET_CART_CLOSE: "SET_CART_CLOSE",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
};
