export const actionsTypes = {
  SET_CART_OPEN: "SET_CART_OPEN",
  SET_CART_CLOSE: "SET_CART_CLOSE",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  ADD_QUANTITY_TO_CART: "ADD_QUANTITY_TO_CART",
  DELETE_QUANTITY_TO_CART: "DELETE_QUANTITY_TO_CART",
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
  CALCULATE_CART_TOTAL: "CALCULATE_CART_TOTAL",
  OPEN_SINGLE_PRODUCT: "OPEN_SINGLE_PRODUCT",
  ADD_SEARCHPHRASE: "ADD_SEARCHPHRASE",
  FILTER_PRODUCTS_BY_NAME: "FILTER_PRODUCTS_BY_NAME",
};
